package com.intellij.lang.javascript.flex;

import com.intellij.facet.FacetConfiguration;
import com.intellij.openapi.projectRoots.Sdk;
import com.intellij.openapi.roots.ModifiableRootModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public abstract class FlexFacetConfiguration implements FacetConfiguration {

  @Nullable
  public abstract Sdk getFlexSdk();

  /**
   * Creates or updates 'AUTOGENERATED library equal to Flex SDK &lt;SDK name&gt;',
   * <code>modifiableRootModel</code> is not committed.<br>
   * <b>Important:</b> If  the module that contains this facet has more than one Flex facets, <code>flexSdk</code> will be set for all of them
   */
  public abstract void setFlexSdk(@NotNull Sdk flexSdk, @NotNull ModifiableRootModel modifiableRootModel);
  
}
